const state={coins:Number(localStorage.getItem("tb_coins")||250),best:Number(localStorage.getItem("tb_best")||0),screen:"home"};
const app=document.getElementById("app");
function save(){localStorage.setItem("tb_coins",state.coins);localStorage.setItem("tb_best",state.best)}
function nav(active){return '<nav class="nav"><button data-nav="home" class="'+(active==="home"?"active":"")+'">🏠<br>Home</button><button data-nav="modes">🎮<br>Modes</button><button data-nav="shop">🛒<br>Shop</button><button data-nav="profile">👤<br>Profile</button></nav>'}
function homeView(){return '<main class="shell"><header class="top"><div class="brand">TAP<span>BOLT</span></div><div class="coin">🪙 '+state.coins+'</div></header><section class="hero"><div class="bolt">⚡</div><h1>TapBolt</h1><p class="tag">Tap Fast. Score More.</p><button class="primary" id="play">PLAY NOW</button></section><section class="card"><div class="row"><div><div class="title">🎯 Daily Challenge</div><div class="muted">Score 2,000 in Rush Mode</div></div><b>+200 🪙</b></div></section><section class="grid"><div class="mini"><b>🏆 Leaderboard</b><span class="muted">Best: '+state.best+'</span></div><div class="mini"><b>🔥 Streak</b><span class="muted">Day 1</span></div></section><section class="card"><div class="row"><div><div class="title">👑 Premium</div><div class="muted">No Ads + 2× earned coins</div></div><b>₹49</b></div></section><section class="card"><div class="title">📱 Android Build</div><div class="muted">Latest APK is published automatically after a successful GitHub Actions build.</div><a class="download" href="https://github.com/akhileshsavali18-beep/TapBolt/releases/download/latest/TapBolt-debug.apk">Download Latest APK</a></section>'+nav("home")+'</main>'}
function gameView(){return '<main class="shell game"><div class="gamehud"><button class="back" id="quit">‹ Home</button><div>⏱️ <b id="time">30</b></div><div>🏆 <b id="score">0</b></div></div><div class="arena" id="arena"></div><div class="bottom-action"><div class="card row"><span>🔥 Combo <b id="combo">0</b></span><span>🪙 <b id="earned">0</b></span></div></div></main>'}
function render(){app.innerHTML=state.screen==="game"?gameView():homeView();if(state.screen==="home")bindHome();if(state.screen==="game")startGame()}
function bindHome(){document.getElementById("play").onclick=()=>{state.screen="game";render()};document.querySelectorAll("[data-nav]").forEach(b=>b.onclick=()=>alert(b.dataset.nav==="modes"?"Modes coming next.":"This section is part of the next build phase."))}
function startGame(){let time=30,score=0,combo=0,earned=0,ended=false;const arena=document.getElementById("arena");const timeEl=document.getElementById("time"),scoreEl=document.getElementById("score"),comboEl=document.getElementById("combo"),earnedEl=document.getElementById("earned");document.getElementById("quit").onclick=()=>{ended=true;state.screen="home";render()};function spawn(){if(ended)return;arena.innerHTML="";const t=document.createElement("button");t.className="target";t.setAttribute("aria-label","Tap target");t.style.left=(Math.random()*Math.max(10,arena.clientWidth-82))+"px";t.style.top=(Math.random()*Math.max(10,arena.clientHeight-82))+"px";t.onclick=()=>{score+=10+Math.min(combo,20)*2;combo++;earned+=5;scoreEl.textContent=score;comboEl.textContent=combo;earnedEl.textContent=earned;spawn()};arena.appendChild(t)}spawn();const timer=setInterval(()=>{time--;timeEl.textContent=time;if(time<=0){clearInterval(timer);ended=true;state.coins+=earned;if(score>state.best)state.best=score;save();showResult(score,earned)}},1000)}
function showResult(score,earned){app.innerHTML='<main class="shell result"><div class="bolt">⚡</div><p class="muted">RUSH COMPLETE</p><div class="bigscore">'+score+'</div><p>+'+earned+' 🪙</p><div class="card"><div class="title">Best Score</div><div class="stat">'+state.best+'</div></div><button class="primary" id="again">PLAY AGAIN</button><button class="download" id="homeBtn">HOME</button></main>';document.getElementById("again").onclick=()=>{state.screen="game";render()};document.getElementById("homeBtn").onclick=()=>{state.screen="home";render()}}
render();